# Generated by Django 6.0 on 2026-09-09 20:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_type', models.CharField(choices=[('income', 'Income / business tax'), ('land', 'Land development tax'), ('vehicle', 'Vehicle tax'), ('other', 'Other')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('reference_number', models.CharField(blank=True, help_text='Challan / receipt number.', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('receipt_url', models.TextField(blank=True)),
                ('expense_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tax_payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('land_area', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('land_unit', models.CharField(choices=[('katha', 'Katha'), ('bigha', 'Bigha'), ('decimal', 'Decimal'), ('shotangsho', 'Shotangsho'), ('acre', 'Acre'), ('kani', 'Kani')], default='katha', max_length=16)),
                ('land_use', models.CharField(choices=[('agricultural', 'Agricultural'), ('residential', 'Residential'), ('commercial', 'Commercial')], default='agricultural', max_length=16)),
                ('location', models.CharField(choices=[('rural', 'Rural (union)'), ('urban', 'Urban (municipal / city)')], default='rural', max_length=16)),
                ('vehicles', models.JSONField(blank=True, default=list)),
                ('income_type', models.CharField(choices=[('agricultural', 'Agricultural'), ('business', 'Business'), ('mixed', 'Mixed')], default='agricultural', max_length=16)),
                ('exemptions', models.DecimalField(decimal_places=2, default=0, help_text='Other exemptions / deductions in BDT.', max_digits=12)),
                ('rebates', models.DecimalField(decimal_places=2, default=0, help_text='Investment tax rebate in BDT.', max_digits=12)),
                ('is_senior', models.BooleanField(default=False, help_text='Age 65+ / eligible for the higher threshold.')),
                ('district', models.CharField(blank=True, max_length=80)),
                ('upazila', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tax_profiles',
            },
        ),
    ]
