# Generated by Django 6.0 on 2026-09-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': False},
        ),
    ]
