# Generated by Django 6.0 on 2026-09-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'managed': False},
        ),
    ]
