# Generated by Django 6.0 on 2026-09-06 16:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raised_role', models.CharField(choices=[('farmer', 'Farmer'), ('doctor', 'Doctor')], max_length=10)),
                ('category', models.CharField(choices=[('no_show', 'No-show'), ('quality_of_care', 'Quality of care'), ('payment', 'Payment disagreement'), ('conduct', 'Conduct'), ('wrong_prescription', 'Wrong prescription'), ('other', 'Other')], max_length=25)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=15)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consultation_disputes',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='consultation',
            table='consultations',
        ),
    ]
