name: featherflow
description: Featherflow - Poultry farm management platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.0.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  http: ^1.2.2
  shared_preferences: ^2.0.0
  phosphor_flutter:
    path: packages/phosphor_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
