# Generated by Django 6.0 on 2026-09-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_workerpayment_workertask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='workerattendance',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='workerpayment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='workertask',
            options={'managed': False},
        ),
    ]
