# Generated by Django 6.0 on 2026-09-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_worker_options_alter_workerattendance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='worker',
            table='workers',
        ),
        migrations.AlterModelTable(
            name='workerattendance',
            table='worker_attendance',
        ),
        migrations.AlterModelTable(
            name='workerpayment',
            table='worker_payments',
        ),
        migrations.AlterModelTable(
            name='workertask',
            table='worker_tasks',
        ),
    ]
