# Generated by Django 6.0 on 2026-09-10 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_id', models.IntegerField()),
                ('plan_code', models.CharField(max_length=50)),
                ('plan_name', models.CharField(max_length=80)),
                ('interval', models.CharField(default='month', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BDT', max_length=5)),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Card (Visa / Mastercard)'), ('bkash', 'bKash'), ('nagad', 'Nagad')], default='', max_length=16)),
                ('provider', models.CharField(default='dev', max_length=24)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='created', max_length=16)),
                ('provider_ref', models.CharField(blank=True, default='', max_length=120)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=80)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=200)),
                ('payment_id', models.UUIDField(blank=True, null=True)),
                ('subscription_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_payment_intents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='billing_pay_user_id_81de55_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('user', 'idempotency_key'), name='billing_intent_idempotency_unique')],
            },
        ),
    ]
