# Generated by Django 6.0 on 2026-09-14 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['created', 'pending', 'succeeded', 'failed', 'cancelled', 'refunded'])), name='billing_intent_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('payment_method__in', ['', 'card', 'bkash', 'nagad'])), name='billing_intent_payment_method_valid'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='billing_intent_amount_positive'),
        ),
    ]
