# Generated by Django 6.0 on 2026-09-14 14:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_paymentintent_billing_intent_status_valid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=24)),
                ('event_id', models.CharField(max_length=200)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='billing.paymentintent')),
            ],
            options={
                'db_table': 'billing_webhook_events',
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='billing_webhook_event_unique')],
            },
        ),
    ]
