# Generated by Django 6.0 on 2026-09-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_paymentintent_billing_intent_status_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='target_type',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('labour_payment', 'Labour payment')], default='subscription', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='plan_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='plan_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='plan_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
