# Generated by Django 6.0 on 2026-09-07 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseRef',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('symptoms', models.JSONField(default=list)),
                ('what_to_do', models.TextField()),
                ('what_not_to_do', models.TextField()),
                ('prevention_tips', models.TextField(blank=True, null=True)),
                ('severity_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10, null=True)),
                ('requires_immediate_vet', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'diseases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiseaseScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farm_id', models.UUIDField(blank=True, db_column='farm_id', null=True)),
                ('flock_id', models.UUIDField(blank=True, db_column='flock_id', null=True)),
                ('image_urls', models.JSONField(default=list)),
                ('image_quality_status', models.CharField(blank=True, choices=[('good', 'Good'), ('blurry', 'Blurry'), ('dark', 'Dark'), ('wrong_angle', 'Wrong angle'), ('rejected', 'Rejected')], default='good', max_length=20, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('severity_level', models.CharField(blank=True, max_length=10, null=True)),
                ('scan_status', models.CharField(blank=True, choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20, null=True)),
                ('is_free_scan', models.BooleanField(default=True)),
                ('chatbot_session_id', models.UUIDField(blank=True, db_column='chatbot_session_id', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'disease_scans',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
