# Generated by Django 6.0 on 2026-09-09 21:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('profile_photo', 'Profile photo'), ('farm_photo', 'Farm photo'), ('council_proof', 'Council registration proof'), ('cv', 'CV / resume'), ('trade_license', 'Trade license'), ('business_registration_cert', 'Business registration certificate'), ('responsible_pharmacist_cert', 'Responsible pharmacist certificate'), ('license_photo', "Driver's license photo"), ('vehicle_photo', 'Vehicle photo'), ('proof_of_work', 'Proof of right to work'), ('ethics_certificate', 'Ethics certificate'), ('publications', 'Publications / portfolio'), ('id_document', 'ID document'), ('certificate', 'Certificate'), ('other', 'Other')], default='other', max_length=40)),
                ('file_path', models.CharField(help_text='Path relative to private_media/.', max_length=255)),
                ('token', models.TextField(help_text='Signed access token (also embedded in the served URL).', unique=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signup_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_signup_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'signup_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'document_type'], name='signup_docu_user_id_83e539_idx')],
            },
        ),
    ]
