# Generated by Django 6.0 on 2026-09-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_farmer_panel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='revenue',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='revenuesource',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='taxrecord',
            options={'managed': False},
        ),
    ]
