# Generated by Django 6.0 on 2026-09-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_options_alter_expensecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expense',
            table='expenses',
        ),
        migrations.AlterModelTable(
            name='expensecategory',
            table='expense_categories',
        ),
        migrations.AlterModelTable(
            name='loan',
            table='loans',
        ),
        migrations.AlterModelTable(
            name='revenue',
            table='revenues',
        ),
        migrations.AlterModelTable(
            name='revenuesource',
            table='revenue_sources',
        ),
        migrations.AlterModelTable(
            name='taxrecord',
            table='tax_records',
        ),
    ]
