# Generated by Django 6.0 on 2026-08-06 21:06

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0002_securityflag_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Payments and refunds',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('audit.adminpanelrecord',),
        ),
    ]
