# Generated by Django 6.0 on 2026-08-06 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_securityflag_supportticket'),
        ('community', '0002_comment_parent_comment_communitynotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Community moderation members',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('audit.adminpanelrecord',),
        ),
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Community reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('audit.adminpanelrecord',),
        ),
    ]
