# Generated by Django 6.0 on 2026-09-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_user_block'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookmark',
            table='bookmarks',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='follow',
            table='follows',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
        migrations.AlterModelTable(
            name='postcategory',
            table='post_categories',
        ),
        migrations.AlterModelTable(
            name='reaction',
            table='reactions',
        ),
    ]
