# Generated by Django 6.0 on 2026-07-30 21:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clinic_hospital_name', models.CharField(max_length=200)),
                ('practice_address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('veterinary_degree', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=200)),
                ('graduation_year', models.PositiveIntegerField()),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('license_issuing_authority', models.CharField(max_length=150)),
                ('license_expiry_date', models.DateField()),
                ('specialty', models.CharField(max_length=150)),
                ('poultry_focus_area', models.TextField(blank=True)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('consultation_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both')], max_length=10)),
                ('cv_url', models.TextField(blank=True)),
                ('council_registration_proof_url', models.TextField()),
                ('prescription_authority', models.BooleanField(default=False)),
                ('emergency_on_call_availability', models.BooleanField(default=False)),
                ('service_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('referral_network', models.TextField(blank=True)),
                ('consent_platform_guidelines', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_doctor_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
