# Generated by Django 6.0 on 2026-07-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
