import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Records the profile models that already exist in profiles/models.py
    and in the real Postgres schema but were never captured in migration
    state (only DoctorProfile was). All managed=False — state bookkeeping
    only, no DDL is issued."""

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_doctorprofile_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farm_name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(max_length=150)),
                ('farm_location', models.TextField()),
                ('farm_address', models.TextField()),
                ('farm_type', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_birds', models.IntegerField(blank=True, null=True)),
                ('farm_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('years_in_farming', models.IntegerField(blank=True, null=True)),
                ('experience_level', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_diseases_faced', models.TextField(blank=True, null=True)),
                ('feed_type', models.CharField(blank=True, max_length=100, null=True)),
                ('feed_sourcing_method', models.TextField(blank=True, null=True)),
                ('existing_vet_consultant', models.CharField(blank=True, max_length=150, null=True)),
                ('farm_photos', models.JSONField(blank=True, null=True)),
                ('number_of_active_workers', models.IntegerField(blank=True, null=True)),
                ('consent_data_collection', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_farmer_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'farmer_profiles', 'managed': False},
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('job_title', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('work_location', models.CharField(blank=True, max_length=150, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateField()),
                ('admin_sub_role', models.CharField(blank=True, max_length=20, null=True)),
                ('tech_skill_level', models.CharField(blank=True, max_length=20, null=True)),
                ('confidentiality_agreement_accepted', models.BooleanField(default=False)),
                ('background_check_consent', models.BooleanField(default=False)),
                ('cv_url', models.TextField(blank=True, null=True)),
                ('previous_experience', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_admin_profiles', to=settings.AUTH_USER_MODEL)),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='managed_admin_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'admin_profiles', 'managed': False},
        ),
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drivers_license_number', models.CharField(max_length=100, unique=True)),
                ('license_class', models.CharField(max_length=50)),
                ('license_expiry_date', models.DateField()),
                ('license_photo_url', models.TextField()),
                ('proof_of_work_url', models.TextField(blank=True, null=True)),
                ('prior_delivery_experience', models.TextField(blank=True, null=True)),
                ('area_coverage', models.TextField(blank=True, null=True)),
                ('availability_schedule', models.JSONField(blank=True, null=True)),
                ('is_online', models.BooleanField(blank=True, default=False, null=True)),
                ('current_status', models.CharField(blank=True, default='offline', max_length=20, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True)),
                ('total_deliveries', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_delivery_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'delivery_profiles', 'managed': False},
        ),
        migrations.CreateModel(
            name='PharmacyOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=200)),
                ('authorized_contact_person', models.CharField(max_length=150)),
                ('business_registration_number', models.CharField(max_length=100, unique=True)),
                ('trade_license_url', models.TextField()),
                ('tax_vat_tin_number', models.CharField(max_length=100)),
                ('business_address', models.TextField()),
                ('warehouse_address', models.TextField(blank=True, null=True)),
                ('number_of_pharmacists', models.IntegerField(blank=True, default=0, null=True)),
                ('responsible_pharmacist_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_pharmacy_organizations', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pharmacy_organization', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'pharmacy_organizations', 'managed': False},
        ),
        migrations.CreateModel(
            name='ResearcherProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=200)),
                ('institutional_email', models.EmailField(max_length=255)),
                ('department', models.CharField(max_length=150)),
                ('highest_degree', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=150)),
                ('university_name', models.CharField(max_length=200)),
                ('graduation_year', models.IntegerField()),
                ('cv_url', models.TextField()),
                ('publications_portfolio_url', models.TextField(blank=True, null=True)),
                ('areas_of_expertise', models.JSONField(blank=True, default=list, null=True)),
                ('years_of_research_experience', models.IntegerField()),
                ('poultry_specific_experience', models.TextField(blank=True, null=True)),
                ('research_role_type', models.CharField(blank=True, max_length=20, null=True)),
                ('ethics_certificate_url', models.TextField(blank=True, null=True)),
                ('conflict_of_interest_declaration', models.BooleanField(default=False)),
                ('publication_consent', models.BooleanField(default=False)),
                ('ip_agreement', models.BooleanField(default=False)),
                ('reference_name', models.CharField(blank=True, max_length=150, null=True)),
                ('reference_title', models.CharField(blank=True, max_length=150, null=True)),
                ('reference_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_researcher_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='researcher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'researcher_profiles', 'managed': False},
        ),
    ]
