# Generated by Django 6.0 on 2026-09-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_admin_shift_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'managed': False},
        ),
    ]
