# Generated by Django 6.0 on 2026-09-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_role_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='user_roles',
        ),
    ]
