# Generated by Django 6.0 on 2026-08-06 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_admin_panel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityFlag',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Security flags',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('audit.adminpanelrecord',),
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Support tickets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('audit.adminpanelrecord',),
        ),
    ]
