# Generated by Django 6.0 on 2026-09-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_admin_rbac'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='adminpanelrecord',
            options={'managed': False, 'ordering': ['created_at']},
        ),
    ]
