# Generated by Django 6.0 on 2026-09-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activitylog',
            table='activity_logs',
        ),
        migrations.AlterModelTable(
            name='adminpanelrecord',
            table='backend_admin_records',
        ),
    ]
