# Generated by Django 6.0 on 2026-07-30 18:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farm_name', models.CharField(max_length=150)),
                ('farm_type', models.CharField(choices=[('broiler', 'Broiler'), ('layer', 'Layer'), ('breeder', 'Breeder'), ('hatchery', 'Hatchery'), ('mixed', 'Mixed'), ('backyard', 'Backyard')], default='mixed', max_length=20)),
                ('location', models.TextField()),
                ('address', models.TextField()),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('total_sheds', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
