# Generated by Django 6.0 on 2026-09-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_flock_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={'managed': False},
        ),
    ]
