# Generated by Django 6.0 on 2026-09-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_alter_farm_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='farm',
            table='farms',
        ),
    ]
