# Generated by Django 6.0 on 2026-07-30 18:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('nutritional_info', models.JSONField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('bag', 'bag'), ('liter', 'liter')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_available', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_restocked_at', models.DateTimeField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=150)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_stock', to='farms.farm')),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='feed.feedtype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('farm', 'feed_type'), name='unique_farm_feed_stock')],
            },
        ),
    ]
