# Generated by Django 6.0 on 2026-07-30 19:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier_name', models.CharField(blank=True, max_length=150)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_purchases', to='farms.farm')),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feed.feedtype')),
            ],
        ),
        migrations.CreateModel(
            name='FeedSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_time', models.TimeField()),
                ('quantity_per_feeding', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('twice_daily', 'Twice daily'), ('custom', 'Custom')], default='daily', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_schedules', to='farms.farm')),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feed.feedtype')),
            ],
        ),
    ]
