# Generated by Django 6.0 on 2026-07-30 20:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('feed', '0002_feedpurchase_feedschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedstock',
            name='stock_status',
            field=models.CharField(choices=[('good', 'Good'), ('low', 'Low'), ('out', 'Out')], default='good', max_length=10),
        ),
        migrations.CreateModel(
            name='FeedOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_orders', to='farms.farm')),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feed.feedtype')),
            ],
        ),
    ]
