# Generated by Django 6.0 on 2026-09-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_feeding_guideline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedpurchase',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='feedpurchase',
            name='feed_type',
        ),
        migrations.AlterModelOptions(
            name='feedschedule',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='feedstock',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='feedtype',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='FeedOrder',
        ),
        migrations.DeleteModel(
            name='FeedPurchase',
        ),
    ]
