# Generated by Django 6.0 on 2026-09-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_remove_feedpurchase_farm_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedschedule',
            table='feed_schedules',
        ),
        migrations.AlterModelTable(
            name='feedstock',
            table='feed_stock',
        ),
        migrations.AlterModelTable(
            name='feedtype',
            table='feed_types',
        ),
    ]
